apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: db
    environment:  development
  name: db
spec:
  replicas: 1
  # Use Recreate to ensure old pod is terminated before creating the new one (prevents PVC attach contention).
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - name: db
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: secrets-db
          env:
            - name: DATASTORE_DB
              value: datastore
            - name: DATASTORE_READONLY_PASSWORD
              value: datastore
            - name: DATASTORE_READONLY_USER
              value: datastore_ro
            - name: PGDATA
              value: /var/lib/postgresql/data
          image: "{{ .Values.webapp.images.postgres }}:{{ .Values.webapp.tag }}"
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: pg-data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - postgres
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data

