apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: home-dir
  name: home-dir
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 10Gi
