apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: site-packages
  name: site-packages
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
