name: Build CKAN Docker 

on:
  #workflow dispatch adds a button to run on github and is useful to always have there
  workflow_dispatch:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
    -  uses: actions/checkout@v2
    
    # Get the date to apply to image tag
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d.%H.%M')" >> $GITHUB_OUTPUT
       
    - name: Extract Metadata for Docker
      id: metadata
      uses: docker/metadata-action@v5
      with:
        tags: ${{ steps.date.outputs.date }}
        images: |
           ghcr.io/${{ github.repository }}  
           
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_TOKEN }}

    -  name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3

    -  name: Set up QEMU
       uses: docker/setup-qemu-action@v1
       with:
         platforms: |
           linux/amd64
           linux/arm64
           
    -  name: NGINX build
       uses: docker/build-push-action@v6
       with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ghcr.io/ncar/sage-dashsearch-nginx:${{ steps.date.outputs.date }}

    -  name: PostgreSQL build
       uses: docker/build-push-action@v6
       with:
          context: ./postgresql
          file: ./postgresql/Dockerfile
          push: true
          tags: ghcr.io/ncar/sage-dashsearch-postgres:${{ steps.date.outputs.date }}

    -  name: SOLR build
       uses: docker/build-push-action@v6
       with:
          context: ./solr
          file: ./solr/Dockerfile
          push: true
          tags: ghcr.io/ncar/sage-dashsearch-solr:${{ steps.date.outputs.date }}
          
    -  name: CKAN build
       uses: docker/build-push-action@v6
       with:
          context: ./ckan
          file: ./ckan/Dockerfile
          build-args: |
            TOKEN=${{ secrets.REPO_TOKEN }}
          push: true
          tags: ghcr.io/ncar/sage-dashsearch-ckan:${{ steps.date.outputs.date }}
      
